---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nativelink-alert
  namespace: flux-system
spec:
  interval: 2m
  path: ./kubernetes/components/alerts
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: ci
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink-infra
    namespace: flux-system
  postBuild:
    substitute:
      PLACEHOLDER_FLAKE_OUTPUT: SET_BY_FLUX
      PLACEHOLDER_CONFIG_MAP_NAME: SET_BY_FLUX
  dependsOn:
    - name: provider
