#:schema ../cargo-with-detailed-deps.json
[package]
edition = "2024"
name = "generate-bazel-rc"
version = "0.1.0"

[dependencies]
toml = { version = "0.8.22", default-features = false, features = [
  "display",
  "parse",
] }

[workspace]
