disallowed-methods = [
  { path = "std::thread::Builder::new", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "std::thread::spawn", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_current_thread", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_multi_thread", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_multi_thread_alt", reason = "use one of the `nativelink-util::task` functions instead", allow-invalid = true }, # Can be invalid because depends on feature flags
  { path = "tokio::runtime::Runtime::block_on", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::new", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::spawn", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::spawn_blocking", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::spawn", reason = "use `nativelink-util::task::spawn` or `nativelink-util::task::background_spawn` instead" },
  { path = "tokio::task::block_in_place", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::task::spawn", reason = "use `nativelink-util::task::spawn` or `nativelink-util::task::background_spawn` instead" },
  { path = "tokio::task::spawn_blocking", reason = "use `nativelink-util::task::spawn_blocking` instead" },
  { path = "tokio::task::spawn_local", reason = "use one of the `nativelink-util::task` functions instead" },
]
# Started from the default at https://doc.rust-lang.org/clippy/lint_configuration.html#doc-valid-idents
doc-valid-idents = [
  "AccessKit",
  "BibLaTeX",
  "BibTeX",
  "CamelCase",
  "ClojureScript",
  "CoAP",
  "CoffeeScript",
  "CoreFoundation",
  "CoreGraphics",
  "CoreText",
  "DevOps",
  "Direct2D",
  "Direct3D",
  "DirectWrite",
  "DirectX",
  "ECMAScript",
  "EiB",
  "FreeBSD",
  "GHz",
  "GPLv2",
  "GPLv3",
  "GiB",
  "GitHub",
  "GitLab",
  "GraphQL",
  "IPv4",
  "IPv6",
  "InfiniBand",
  "JavaScript",
  "KiB",
  "LaTeX",
  "MHz",
  "MiB",
  "MinGW",
  "NaN",
  "NaNs",
  "NetApp",
  "NetBSD",
  "NixOS",
  "OAuth",
  "OCaml",
  "OpenAL",
  "OpenBSD",
  "OpenDNS",
  "OpenExr",
  "OpenGL",
  "OpenMP",
  "OpenSSH",
  "OpenSSL",
  "OpenStreetMap",
  "OpenTelemetry",
  "OpenType",
  "PiB",
  "PostScript",
  "PowerPC",
  "PowerShell",
  "PureScript",
  "RoCE",
  "THz",
  "TeX",
  "TensorFlow",
  "TiB",
  "TrueType",
  "TypeScript",
  "WebAssembly",
  "WebGL",
  "WebGL2",
  "WebGPU",
  "WebP",
  "WebRTC",
  "WebSocket",
  "WebTransport",
  "YCbCr",
  "iOS",
  "macOS",
  "sRGB",
]
msrv = "1.93.1"
