
#!/bin/bash
# Copyright 2024 The NativeLink Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This is a script for adding version information and the git commit hash
# as run time environment variables in .bazelrc.

# Ensure the script exits if any command fails.
set -e

# Generate application version and git commit hash.
APP_VERSION=$(grep '^version' Cargo.toml | cut -d '"' -f 2)
GIT_COMMIT_HASH=$(git rev-parse HEAD)

# Define variables.
COMMENT_LINE="# Generated by update_bazelrc.sh"
APP_VERSION_PREFIX="build --action_env=NATIVELINK_APP_VERSION="
GIT_COMMIT_HASH_PREFIX="build --action_env=NATIVELINK_GIT_COMMIT_HASH="
APP_VERSION_LINE="$APP_VERSION_PREFIX$APP_VERSION"
GIT_COMMIT_HASH_LINE="$GIT_COMMIT_HASH_PREFIX$GIT_COMMIT_HASH"

# Append comment line.
if ! grep -q "$COMMENT_LINE" .bazelrc; then
    echo "" >> .bazelrc
    echo "$COMMENT_LINE" >> .bazelrc
fi

# Update or append APP_VERSION line.
if grep -q "^$APP_VERSION_PREFIX" .bazelrc; then
    sed -i "s|^$APP_VERSION_PREFIX.*|$APP_VERSION_LINE|" .bazelrc
else
    echo "$APP_VERSION_LINE" >> .bazelrc
fi

# Update or append GIT_COMMIT_HASH line.
if grep -q "^$GIT_COMMIT_HASH_PREFIX" .bazelrc; then
    sed -i "s|^$GIT_COMMIT_HASH_PREFIX.*|$GIT_COMMIT_HASH_LINE|" .bazelrc
else
    echo "$GIT_COMMIT_HASH_LINE" >> .bazelrc
fi
