[package]
edition = "2024"
name = "nativelink-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
nativelink-config = { path = "../../nativelink-config" }
nativelink-error = { path = "../../nativelink-error" }
nativelink-proto = { path = "../../nativelink-proto" }
nativelink-scheduler = { path = "../../nativelink-scheduler" }
nativelink-util = { path = "../../nativelink-util" }

arbitrary = { version = "1", features = ["derive"] }
futures = { version = "0.3", default-features = false }
libfuzzer-sys = "0.4"
mock_instant = { version = "0.5.3", default-features = false }
serde_json5 = { version = "0.2.1", default-features = false }
tokio = { version = "1", features = ["rt", "sync", "time", "test-util"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[lib]
path = "src/lib.rs"


[[bin]]
bench = false
doc = false
name = "cas_config"
path = "fuzz_targets/cas_config.rs"
test = false

[[bin]]
bench = false
doc = false
name = "scheduler_race"
path = "fuzz_targets/scheduler_race.rs"
test = false
