---
name: Prepare Nix
description: "Common setup for all runs using Nix."
inputs:
  nativelink_attic_token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: ./.github/actions/free-disk

    - name: Install Nix
      uses: >- # https://github.com/nixbuild/nix-quick-install-action/releases/tag/v35
        nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c
      with:
        nix_version: 2.34.7
        nix_conf: |
          fallback = true # So we always work even if the cache is down
          log-lines = 100 # Necessary in CI to get enough failure context
          keep-outputs = true # Don't delete non-root outputs, because might be needed for other builds

    # only doing the cache around attic for now to avoid massive Nix caches overloading
    # Github cache
    - uses: >- # https://github.com/nix-community/cache-nix-action/releases/tag/v7
        nix-community/cache-nix-action/restore@7df957e333c1e5da7721f60227dbba6d06080569
      id: restore-cache
      with:
        primary-key: ${{ runner.os }}-nix-attic-cache

    - name: Setup attic cache
      uses: >- # v4
        nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_wait_seconds: 30 # if we're failing, we want to wait a reasonable amount of time
        command: |
          set -euo pipefail
          date
          cd /tmp
          nix build nixpkgs#attic-client
          # Note NATIVELINK_ATTIC_TOKEN is blank for PR builds as they don't have secret access
          ./result/bin/attic login uc1-dev https://attic.uc1.scdev.nativelink.net/ ${{ inputs.nativelink_attic_token }}
          ./result/bin/attic use nativelink

          if [ -n "${{ inputs.nativelink_attic_token }}" ]; then
            # If we don't have a token, we can't push!

            # Replace with more reliable attic for working around
            # * https://github.com/zhaofengli/attic/issues/226
            # * https://github.com/zhaofengli/attic/pull/317
            # We use the original one first to get caching of this
            nix build github:TraceMachina/attic
            RUST_BACKTRACE=full RUST_LOG=debug,hyper_util=info,rustls=info ./result/bin/attic watch-store nativelink &> attic-push.log &

            # For the cases where we don't have a cache of it, push it
            ./result/bin/attic push nativelink $(nix eval --raw github:TraceMachina/attic)
          fi
        shell: bash

    - uses: >- # https://github.com/nix-community/cache-nix-action/releases/tag/v7
        nix-community/cache-nix-action/save@7df957e333c1e5da7721f60227dbba6d06080569
      with:
        primary-key: ${{ steps.restore-cache.outputs.primary-key }}
