---
name: Prepare Nix
description: "Common setup for all runs using Nix."
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: ./.github/actions/free-disk

    - name: Install Nix
      uses: >- # https://github.com/DeterminateSystems/nix-installer-action/releases/tag/v22
        DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      with:
        source-tag: v3.13.0

    # FIXME(palfrey): Replace with better cache. Workers are currently taking minutes to upload data
    # all the time, probably because we're at ~500GB of 10GB in the cache storage and it's breaking.
    # We've tried Flakehub, but it doesn't work for us because it assumes "branches on an org repo"
    # not our "fork and branch on your own repo" setup for it's auth so we can't currently use that.

    # - name: Add Nix magic cache
    #   uses: >- # https://github.com/DeterminateSystems/magic-nix-cache-action/releases/tag/v13
    #     DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
    #   with:
    #     source-tag: v0.1.6
