---
name: Prepare Nix
description: "Common setup for all runs using Nix."
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: >- # v2.0.0
        endersonmenezes/free-disk-space@3f9ec39ebae520864ac93467ee395f5237585c21
      with:
        remove_android: false # Takes too long.
        remove_dotnet: true
        remove_haskell: true
        remove_tool_cache: false # TODO(palfrey): Do we really need this?
        # Note: Not deleting google-cloud-cli because it takes too long.
        remove_packages: >
          azure-cli
          microsoft-edge-stable
          google-chrome-stable
          firefox
          postgresql*
          temurin-*
          *llvm*
          mysql*
          dotnet-sdk-*
        remove_packages_one_command: true
        remove_folders: >
          /usr/share/swift
          /usr/share/miniconda
          /usr/share/az*
          /usr/share/glade*
          /usr/local/lib/node_modules
          /usr/local/share/chromium
          /usr/local/share/powershell

    - name: Delete platform specific items to free up disk space
      shell: bash
      run: |
        if [ "$(uname)" = "Darwin" ]; then
          echo "Deleting Applications"
          sudo rm -rf ~/Applications/*
          echo "Deleting all iOS simulators"
          xcrun simctl delete all
          echo "Deleting iOS Simulator caches"
          sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
        else
          echo "Nothing to do here."
        fi

    - name: Install Nix
      uses: >- # https://github.com/DeterminateSystems/nix-installer-action/releases/tag/v20
        DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196
      with:
        source-tag: v3.13.0

    # FIXME(palfrey): Replace with better cache. Workers are currently taking minutes to upload data
    # all the time, probably because we're at ~500GB of 10GB in the cache storage and it's breaking.
    # We've tried Flakehub, but it doesn't work for us because it assumes "branches on an org repo"
    # not our "fork and branch on your own repo" setup for it's auth so we can't currently use that.

    # - name: Add Nix magic cache
    #   uses: >- # https://github.com/DeterminateSystems/magic-nix-cache-action/releases/tag/v13
    #     DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
    #   with:
    #     source-tag: v0.1.6
