---
name: Prepare Nix
description: "Common setup for all runs using Nix."
inputs:
  nativelink_attic_token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: ./.github/actions/free-disk

    - name: Install Nix
      uses: >- # https://github.com/DeterminateSystems/nix-installer-action/releases/tag/v22
        DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      with:
        source-tag: v3.13.0

    - name: Setup attic cache
      uses: >- # v4
        nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: |
          cd /tmp
          nix build nixpkgs#attic-client
          # Note NATIVELINK_ATTIC_TOKEN is blank for PR builds as they don't have secret access
          ./result/bin/attic login uc1-dev https://attic.uc1.scdev.nativelink.net/ ${{ inputs.nativelink_attic_token }}
          ./result/bin/attic use nativelink

          # Replace with more reliable attic for working around
          # * https://github.com/zhaofengli/attic/issues/226
          # * https://github.com/zhaofengli/attic/pull/317
          # We use the original one first to get caching of this
          nix build github:TraceMachina/attic
          RUST_BACKTRACE=full RUST_LOG=debug,hyper_util=info,rustls=info ./result/bin/attic watch-store nativelink &> attic-push.log &

          # For the cases where we don't have a cache of it, push anyways
          ./result/bin/attic push nativelink $(nix eval --raw github:TraceMachina/attic)
        shell: bash
