---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../resources/flux
- ../../resources/nativelink-core
- ../../resources/gateway-routes
- ../../workers/resources/worker-init
- ../../workers/resources/siso-chromium
