// AUTOGENERATED by scripts/gen-config-reference.mjs — do not edit by hand.
// Regenerate: bun run --filter=@nativelink/docs gen:config-reference

export interface ConfigVersion {
  /** Display version, e.g. "v1.5.0" or "main". */
  version: string;
  /** Human label shown in the switcher, e.g. "v1.5.0 (latest)". */
  label: string;
  /** Route for this version's reference page. */
  href: string;
  /** Git ref the page was generated from. */
  ref: string;
  /** Whether this is the canonical (latest stable) page. */
  isLatest: boolean;
  /** Whether this is the in-development ("main") page. */
  isDev: boolean;
}

export const CONFIG_REFERENCE_BASE = "/reference/nativelink-config";

export const CONFIG_VERSIONS: ConfigVersion[] = [
  {
    "version": "main",
    "label": "main (experimental)",
    "href": "/reference/nativelink-config/main",
    "ref": "main",
    "isLatest": false,
    "isDev": true
  },
  {
    "version": "v1.5.0",
    "label": "v1.5.0 (latest)",
    "href": "/reference/nativelink-config",
    "ref": "v1.5.0",
    "isLatest": true,
    "isDev": false
  },
  {
    "version": "v1.4.0",
    "label": "v1.4.0",
    "href": "/reference/nativelink-config/v1.4.0",
    "ref": "v1.4.0",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.3.2",
    "label": "v1.3.2",
    "href": "/reference/nativelink-config/v1.3.2",
    "ref": "v1.3.2",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.3.1",
    "label": "v1.3.1",
    "href": "/reference/nativelink-config/v1.3.1",
    "ref": "v1.3.1",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.3.0",
    "label": "v1.3.0",
    "href": "/reference/nativelink-config/v1.3.0",
    "ref": "v1.3.0",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.2.0",
    "label": "v1.2.0",
    "href": "/reference/nativelink-config/v1.2.0",
    "ref": "v1.2.0",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.1.0",
    "label": "v1.1.0",
    "href": "/reference/nativelink-config/v1.1.0",
    "ref": "v1.1.0",
    "isLatest": false,
    "isDev": false
  },
  {
    "version": "v1.0.0",
    "label": "v1.0.0",
    "href": "/reference/nativelink-config/v1.0.0",
    "ref": "v1.0.0",
    "isLatest": false,
    "isDev": false
  }
];
