import { Callout } from "@/components/callout";
import { ConfigVersionSwitcher } from "@/components/config-version-switcher";
import { Mermaid } from "@/components/mermaid";
import { MinVersion } from "@/components/min-version";
import { NextStep } from "@/components/next-step";
import { Rung } from "@/components/rung";
import { SourceLink } from "@/components/source-link";
import { Steps } from "@/components/steps";
import { VerifyBlock } from "@/components/verify-block";
import { Accordion, Accordions } from "fumadocs-ui/components/accordion";
import { Callout as FumadocsCallout } from "fumadocs-ui/components/callout";
import { Tab, Tabs } from "fumadocs-ui/components/tabs";
import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    // Our themed Callout takes precedence over Fumadocs's default;
    // expose Fumadocs's as FumaCallout if anyone wants the original style.
    Callout,
    FumaCallout: FumadocsCallout,
    // Version toggle embedded on the autogenerated config-reference pages.
    ConfigVersionSwitcher,
    Steps,
    Tabs,
    Tab,
    Mermaid,
    Accordions,
    Accordion,
    // The journey components. Every page in an ordered track opens with
    // <Rung> and closes with <NextStep>; every tutorial and how-to proves
    // itself with <VerifyBlock>; behavioural claims carry a <SourceLink>.
    Rung,
    NextStep,
    VerifyBlock,
    SourceLink,
    MinVersion,
    ...components,
  };
}
