# Copyright 2024 The NativeLink Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is @generated by lre-rs.

"""Module extension to register different lre-rs tool repositories."""

load("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

# TODO(palfrey): Using module extensions here isn't optimal as it doesn't
#                    allow overriding tools via environment variables.
#                    Unfortunately rules_rust's rust_toolchain currently
#                    requires tools to be declared via labels to filegroups,
#                    so we need the new_local_repository approach here.
#                    Add support for raw strings to rules_rust upstream so
#                    that we can remove this module extension entirely.

def _lre_rs_impl(_mctx):
    new_local_repository(
        name = "lre-rs-stable-aarch64-darwin",
        build_file = "@local-remote-execution//rust:aarch64-darwin.BUILD.bazel",
        path = "/nix/store/f9228dfh6xlcmfzgqb4ai348x0b5kb1j-rust-default-1.93.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-aarch64-darwin",
        build_file = "@local-remote-execution//rust:aarch64-darwin.BUILD.bazel",
        path = "/nix/store/g070yl22yhf4qm6x7gnzszd270i01245-rust-default-1.95.0-nightly-2026-02-03",
    )
    new_local_repository(
        name = "lre-rs-stable-aarch64-linux",
        build_file = "@local-remote-execution//rust:aarch64-linux.BUILD.bazel",
        path = "/nix/store/70yycw0h3ilqyc9gijnagynmri5byk2j-rust-default-1.93.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-aarch64-linux",
        build_file = "@local-remote-execution//rust:aarch64-linux.BUILD.bazel",
        path = "/nix/store/sg6hi09lkmnqn9p398ryvph6zqwqjb42-rust-default-1.95.0-nightly-2026-02-03",
    )
    new_local_repository(
        name = "lre-rs-stable-x86_64-darwin",
        build_file = "@local-remote-execution//rust:x86_64-darwin.BUILD.bazel",
        path = "/nix/store/rzpmik22n5xs6ghyfvrc4qc3ydrig5m1-rust-default-1.93.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-x86_64-darwin",
        build_file = "@local-remote-execution//rust:x86_64-darwin.BUILD.bazel",
        path = "/nix/store/kljcaa7rzrs992w4ww2x5sm4fzzb3mz6-rust-default-1.95.0-nightly-2026-02-03",
    )
    new_local_repository(
        name = "lre-rs-stable-x86_64-linux",
        build_file = "@local-remote-execution//rust:x86_64-linux.BUILD.bazel",
        path = "/nix/store/5vrcxn6gaimj3dixshf5w03qidc66223-rust-default-1.93.0",
    )
    new_local_repository(
        name = "lre-rs-nightly-x86_64-linux",
        build_file = "@local-remote-execution//rust:x86_64-linux.BUILD.bazel",
        path = "/nix/store/2izrdn6b1fnsr7zxxf646mgvsk8afx8j-rust-default-1.95.0-nightly-2026-02-03",
    )

lre_rs = module_extension(implementation = _lre_rs_impl)
