"use client";

import { CONFIG_VERSIONS } from "@/lib/config-versions";
import { usePathname, useRouter } from "next/navigation";

/**
 * Version toggle for the autogenerated NativeLink configuration reference.
 *
 * Each supported version (every `v1.x` release plus `main`) is its own
 * statically generated page; this control simply navigates between them. The
 * current version is derived from the pathname, so the component takes no
 * props and the generator embeds a bare `<ConfigVersionSwitcher />` on every
 * page. The version list comes from `@/lib/config-versions`, which is
 * regenerated alongside the pages by `scripts/gen-config-reference.mjs`.
 */
export function ConfigVersionSwitcher() {
  const router = useRouter();
  const pathname = (usePathname() ?? "").replace(/\/$/, "");

  // Longest matching href wins so `/…/main` doesn't match the base `/…`.
  const current =
    [...CONFIG_VERSIONS]
      .sort((a, b) => b.href.length - a.href.length)
      .find((v) => pathname === v.href) ?? CONFIG_VERSIONS[0];

  // The generated manifest is never empty, but guard so the type narrows.
  if (!current) return null;

  return (
    <div className="not-prose mb-6 flex items-center gap-2 text-sm">
      <label htmlFor="config-version" className="font-medium text-fd-muted-foreground">
        Version
      </label>
      <select
        id="config-version"
        value={current.version}
        onChange={(e) => {
          const next = CONFIG_VERSIONS.find((v) => v.version === e.target.value);
          if (next && next.version !== current.version) router.push(next.href);
        }}
        className="rounded-md border border-fd-border bg-fd-card px-2 py-1 font-medium text-fd-foreground shadow-sm outline-none focus:ring-2 focus:ring-fd-ring"
      >
        {CONFIG_VERSIONS.map((v) => (
          <option key={v.version} value={v.version}>
            {v.label}
          </option>
        ))}
      </select>
    </div>
  );
}
