---
name: Build local project against NativeLink

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  local:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
        exclude:
          - os: macos-15
    name: Local / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: >- # v4.2.2
          actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Nix
        uses: >- # v17
          DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3

      - name: Build project
        run: nix develop -c bazel build ...
