---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  targetNamespace: tekton-pipelines
  pruner:
    resources:
    - pipelinerun
    - taskrun
    keep: 100
    # Clean up every 20 minutes.
    schedule: "*/20 * * * *"
  pipeline:
    disable-affinity-assistant: true
    coschedule: pipelineruns
