{
  buildImage,
  pullImage,
}:
buildImage {
  name = "toolchain-drake";
  # imageDigest and sha256 are generated by toolchain-drake.sh for non-reproducible builds.
  fromImage = pullImage {
    imageName = "localhost:5001/toolchain-drake";
    imageDigest = ""; # DO NOT COMMIT DRAKE IMAGE_DIGEST VALUE
    sha256 = ""; # DO NOT COMMIT DRAKE SHA256 VALUE
    tlsVerify = false;
    arch = "amd64";
    os = "linux";
  };
}
