---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-alert
  namespace: ci
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: ${PLACEHOLDER_FLAKE_OUTPUT}
    configMapName: ${PLACEHOLDER_CONFIG_MAP_NAME}
