name: NativeLink Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '!tools/benchmark/**'  # Exclude benchmark config changes from triggering
  pull_request:
    paths:
      - '!tools/benchmark/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v4
        with:
          repository: TraceMachina/nativelink-benchmarks
          ref: main  # Specify branch explicitly
          path: benchmarks
          
      - name: Checkout NativeLink
        uses: actions/checkout@v4
        with:
          path: nativelink

      - name: Setup benchmark environment
        run: |
          cd benchmarks
          python3 -m pip install -r requirements.txt

      - name: Run external benchmarks
        run: |
          cd benchmarks
          python3 enhanced_benchmark_workflow.py \
            --nativelink-repo=../nativelink \
            --commit=${{ github.sha }} \
            --nativelink-url=${{ vars.NATIVELINK_ENDPOINT }} \
            --api-key=${{ secrets.NATIVELINK_API_KEY }}