---
name: Create OCI image
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  get-images-matrix:
    runs-on: ubuntu-24.04
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set Images matrix
        id: setmatrix
        run: |
          MATRIX_STRINGIFIED=$(jq -c . < .github/images-matrix.json)
          echo "matrix=$MATRIX_STRINGIFIED" >> $GITHUB_OUTPUT

  publish-image:
    needs: get-images-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-images-matrix.outputs.matrix) }}
    name: Publish ${{ matrix.image }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      security-events: write
    timeout-minutes: 90
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

      - name: Set up Docker
        id: docker
        uses: >- # v5.2.0
          docker/setup-docker-action@0234bb73ccb40f0c430b795634f9247e2b5c2d23
        if: runner.os == 'macOS' # already setup for Linux
        env:
          # m1 chips, as seen in the GitHub CI, don't support nested hardware virtualization.
          #
          # We need `-machine virt` to stop Lima from providing `accel=hvf`due to this
          # [QEMU issue](https://gitlab.com/qemu-project/qemu/-/issues/2981).
          #
          # We also need `-cpu *` to stop Lima from providing `-cpu host` as:
          # 1) `-cpu host` requires `kvm` or `hvf` (which we don't have)
          # 2) `-cpu host` implies `host-phys-bits=on` which is borked in this environment
          # From which CPU to actually emulate, we choose what will be the most performant.
          #
          # We accomplish both of these goals with the methodology from
          # [this comment](https://github.com/lima-vm/lima/pull/3173#issuecomment-2623130310).
          QEMU_SYSTEM_AARCH64: "qemu-system-aarch64 -machine virt -cpu max,pmu=off,sve=on,sve128=on,sme=off,pauth=off"

      - name: Set docker host
        if: runner.os == 'macOS' # already setup for Linux
        run: |
          echo "DOCKER_HOST=${{steps.docker.outputs.sock}}" >> "$GITHUB_ENV"

      - id: version
        uses: ./.github/actions/generate-version

      - name: Test and upload ${{ matrix.image }}
        uses: ./.github/actions/test-and-upload-image
        with:
          image: ${{ matrix.image }}
          multi-arch: ${{ matrix.multi-arch }}
          components: ${{ matrix.components }}
          tag: ${{ steps.version.outputs.version-string }}
          GHCR_USERNAME: ${{ vars.GHCR_PUBLISH_USER }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PUBLISH_TOKEN }}

      - name: Upload trivy scan results to GitHub Security tab
        uses: >- # v4.36.2
          github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: 'trivy-results.sarif'
        if: ${{ contains(fromJson('["refs/heads/main", "refs/pull/2457/merge"]'), github.ref) }}

      - name: Teardown Worker
        uses: ./.github/actions/end-nix
        if: always()
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}
