---
name: Create OCI image
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  get-images-matrix:
    runs-on: ubuntu-24.04
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set Images matrix
        id: setmatrix
        run: |
          MATRIX_STRINGIFIED=$(jq -c . < .github/images-matrix.json)
          echo "matrix=$MATRIX_STRINGIFIED" >> $GITHUB_OUTPUT

  publish-image:
    needs: get-images-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-images-matrix.outputs.matrix) }}
    name: Publish ${{ matrix.image }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      security-events: write
    timeout-minutes: 90
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Skopeo login otherwise complains with
      # "get credentials: loading registries configuration \"/etc/containers/registries.conf\": registries.conf must be in v2 format but is in v1"
      - name: Upgrade registries config to v2
        run: |
          cat /etc/containers/registries.conf
          echo "unqualified-search-registries = [\"docker.io\", \"quay.io\"]" | sudo tee /etc/containers/registries.conf

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

      - id: version
        uses: ./.github/actions/generate-version

      - name: Test and upload ${{ matrix.image }}
        uses: ./.github/actions/test-and-upload-image
        with:
          image: ${{ matrix.image }}
          multi-arch: ${{ matrix.multi-arch }}
          components: ${{ matrix.components }}
          tag: ${{ steps.version.outputs.version-string }}
          GHCR_USERNAME: ${{ vars.GHCR_PUBLISH_USER }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PUBLISH_TOKEN }}

      - name: Upload trivy scan results to GitHub Security tab
        uses: >- # v4.36.2
          github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: 'trivy-results.sarif'
        if: ${{ contains(fromJson('["refs/heads/main", "refs/pull/2457/merge"]'), github.ref) }}

      - name: Teardown Worker
        uses: ./.github/actions/end-nix
        if: always()
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}
