# ---
name: Local Remote Execution

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  local:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-26]
        toolchain: [lre-cc, lre-rs]
        exclude:
          - os: macos-26
            toolchain: lre-cc
    name: Local / ${{ matrix.toolchain }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

      - name: Build example with ${{ matrix.toolchain }} toolchain
        env:
          TOOLCHAIN: ${{ matrix.toolchain }}
        run: >
          nix develop --impure --fallback --command
          bash -c "bazel run \
           --lockfile_mode=error \
           --verbose_failures \
           @local-remote-execution//examples:${TOOLCHAIN}"

      - name: Teardown Worker
        uses: ./.github/actions/end-nix
        if: always()
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

  remote-docker-compose:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: >- # v6.0.2
        actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up Docker Buildx
      uses: >- # v3.9.0
        docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

    - name: Prepare Worker
      uses: ./.github/actions/prepare-nix
      with:
        nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

    - name: Build Nativelink images
      run: |
        nix run .#image.copyTo docker-daemon:local-nativelink:latest
        nix run .#nativelink-worker-lre-rs.copyTo docker-daemon:local-worker-rs:latest
        nix run .#nativelink-worker-init.copyTo docker-daemon:local-worker-init:latest

    - name: Compile NativeLink with NativeLink
      timeout-minutes: 60
      run: |
        set -eu
        mkdir .cache
        cd deployment-examples/docker-compose
        docker compose -f docker-compose-lre.yml up &> docker-compose.log &
        cd ../../
        nix develop --impure --fallback --command \
        bash -c "bazel test //... \
           --lockfile_mode=error \
           --verbose_failures \
           --remote_cache=grpc://127.0.0.1:50051 \
           --remote_executor=grpc://127.0.0.1:50052"
      env:
          NATIVELINK_IMAGE: local-nativelink:latest
          NATIVELINK_WORKER_INIT_IMAGE: local-worker-init:latest
          NATIVELINK_LRE_IMAGE: local-worker-rs:latest
          NATIVELINK_DIR: ${{ github.workspace }}/.cache
          RUST_LOG: debug

    - name: Check Docker compose
      run: cat deployment-examples/docker-compose/docker-compose.log
      if: always()

    - name: Teardown Worker
      uses: ./.github/actions/end-nix
      if: always()
      with:
        nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}
