name: CI

# Controls when the workflow will run.
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  integration-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: >- # v6.0.2
        actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up Docker Buildx
      uses: >- # v3.9.0
        docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

    - name: Build image
      uses: >- # v6.13.0
        docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
      with:
        context: .
        file: ./deployment-examples/docker-compose/Dockerfile
        build-args: |
          OPT_LEVEL=fastbuild
          ADDITIONAL_BAZEL_FLAGS=--extra_toolchains=@rust_toolchains//:all
        load: true # This brings the build into `docker images` from buildx.
        tags: trace_machina/nativelink:latest

    - name: Run tests
      run: ./run_integration_tests.sh
