---
name: Deploy NativeLink Web
on:
  push:
    branches: [main]
    paths:
      - 'web/platform/**'
      - '**/*.md'
      - 'nativelink-config/**'
      - 'tools/**'
      - '**/*.lock'
      - '**/*.nix'
  pull_request:
    branches: [main]
    paths:
      - 'web/platform/**'
      - '**/*.md'
      - 'nativelink-config/**'
      - 'tools/**'
      - '**/*.lock'
      - '**/*.nix'

permissions: read-all

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-26
    name: Web Platform Deployment / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: >- # v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Prepare Worker
        uses: ./.github/actions/prepare-nix
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}

      - name: Test Build
        if: github.event_name == 'pull_request'
        working-directory: web/platform
        run: |
          nix develop --fallback --impure --command bash -c "
            bun setup && bun docs && bun run build
          "

      - name: Production deployment
        if: >-
          matrix.os == 'ubuntu-24.04'
          && github.ref == 'refs/heads/main'
          && env.CLOUDFLARE_API_TOKEN != ''
        working-directory: web/platform
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler
        run: |
          nix develop --fallback --impure --command bash -c "
            bun install && \
            bun docs && \
            bun run build && \
            bun wrangler deploy
          "

      - name: Teardown Worker
        uses: ./.github/actions/end-nix
        if: always()
        with:
          nativelink_attic_token: ${{ secrets.NATIVELINK_ATTIC_TOKEN }}
